name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:  # Example adapted from https://docs.github.com/en/actions/quickstart
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow-related metadata to console
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your repository is ${{ github.repository }} and will be cloned in the next step."

      - name: Checkout Git repository code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
          ls ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret to console (Frowned upon. GitHub encrypts your secrets!)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo "SSH_HOST=${SSH_HOST}"
          echo "SSH_HOST=${SSH_HOST}" | sed 's/[.]/-/g'  # replaces dots with dashes
